export const mavens = {
  aggie: {
    first: "Aggie",
    last: "Burns",
    key: "aggie",
    slug: "aggie",
    text: "Are your puzzle senses zinging? Just like Aggie, you're straight forward and insightful. Maybe just a little awkward, but you make it work for you.",
  },
  shannon: {
    first: "Shannon",
    last: "Lake",
    key: "shannon",
    slug: "shannon-lake",
    text: "You've perfected the look! Just like Shannon, you've had to work hard for everything you have. You're detail-oriented and fiercely independent.",
  },
  maude: {
    first: "Maude",
    last: "Elders",
    key: "maude",
    slug: "maude-elders",
    text: "Circle the wagons! Just like Maude, you value a close knit community and good home-cooked meal.  Your intuition tells you all you need to know.",
  },
  mary_jo: {
    first: "Mary Jo",
    last: "Jefferson",
    key: "mary_jo",
    slug: "mary-jo-jefferson",
    text: "Free spirits unite! Just like Mary Jo, you've got a sense of humor and adventure. You may be slightly eccentric, but you always see the big picture.",
  },
  eleanor: {
    first: "Eleanor",
    last: "Marsdale",
    key: "eleanor",
    slug: "eleanor-marsdale",
    text: "Ready to get to work? Just like Eleanor, you're no-nonsense. You like efficiency, planning, and marking things off your list. Let's get cracking!",
  },
  jordan: {
    first: "Jordan",
    last: "",
    key: "jordan",
    slug: null,
    text: "What's the emergency? Just like Jordan, you think quickly on your feet. You can triage any problem you face with calmness and sensibility.",
  },
  tess: {
    first: "Tess",
    last: "Windsor",
    key: "tess",
    slug: "tess-windsor",
    text: "Welcome to the upper echelon. Just like Tess, you know how to entertain friends and foes with a glass of wine and a quick wit.",
  },
  lulu: {
    first: "Lulu",
    last: "",
    key: "lulu",
    slug: null,
    text: "Call in the Expert! Just like Tess, you know your stuff in and out. With an eye for detail, you want to know how everything works.",
  },
  desiree: {
    first: "Desiree",
    last: "Broussard",
    key: "desiree",
    slug: "desiree-broussard",
    text: "Come out and Play! Just like Desiree, you're a sultry woman with extraordinary needs. You could charm the pants of anyone you desire.",
  },
  natasha: {
    first: "Natasha",
    last: "",
    key: "natasha",
    slug: null,
    text: "Cooking up a mystery? Just like Natasha, you have a refined palate. You're secretive about your work, but you are the hardest working Maven.",
  },
};

export const questions = [
  {
    key: 0,
    text: "Out on the town for the night? What are you wearing?",
    choices: [
      { text: "Sensible shoes", maven: "aggie" },
      { text: "Haute couture", maven: "shannon" },
      { text: "Something loud & showy", maven: "maude" },
      { text: "Diamond earrings", maven: "tess" },
      { text: "Low-cut dress & a travel bag", maven: "desiree" },
    ],
  },
  {
    key: 1,
    text: "Stranded in paradise? What book are you reading?",
    choices: [
      { text: "The Good Earth", maven: "aggie" },
      { text: "Style Maker (magazine)", maven: "shannon" },
      { text: "Mothers and Daughters: Bridging the Divide", maven: "eleanor" },
      { text: "First Aid in the Wild", maven: "jordan" },
      { text: "Native Birds and Their Habitats", maven: "lulu" },
    ],
  },
  {
    key: 2,
    text: "Company coming? What are you serving?",
    choices: [
      { text: "A full table of home-cooked comfort foods", maven: "maude" },
      { text: "Coffee and toast", maven: "eleanor" },
      { text: "Expensive catering", maven: "tess" },
      { text: "Ambrosia and strawberries", maven: "desiree" },
      { text: "Leg of lamb in a light remoulade", maven: "natasha" },
    ],
  },
  {
    key: 3,
    text: "Afternoon off? What sounds good?",
    choices: [
      { text: "Gardening and a nap", maven: "aggie" },
      { text: "Attending a fashion show", maven: "shannon" },
      { text: "Deep tissue massage", maven: "mary_jo" },
      { text: "Data entry", maven: "lulu" },
      { text: "Hot red pedicure", maven: "desiree" },
    ],
  },
  {
    key: 4,
    text: "Need to brag? What's your biggest asset?",
    choices: [
      { text: "Lifting myself up from my bootstraps", maven: "shannon" },
      { text: "My wit", maven: "mary_jo" },
      { text: "Getting the most from my people", maven: "eleanor" },
      { text: "My social network", maven: "tess" },
      { text: "Preparing delicacies", maven: "natasha" },
    ],
  },
  {
    key: 5,
    text: "Need a buddy? What trait are you looking for?",
    choices: [
      { text: "Shopping buddy", maven: "shannon" },
      { text: "Someone with a mother's sensibility", maven: "maude" },
      { text: "A keen sense of humor", maven: "mary_jo" },
      { text: "Anyone with an independent streak", maven: "jordan" },
      { text: "A fellow foodie", maven: "natasha" },
    ],
  },
  {
    key: 6,
    text: "Having a good morning? What are you drinking?",
    choices: [
      { text: "I'd like a coffee with my sugar and creamer", maven: "aggie" },
      { text: "Water", maven: "shannon" },
      { text: "Black coffee", maven: "eleanor" },
      { text: "Protein shake", maven: "jordan" },
      { text: "Bloody Mary", maven: "tess" },
    ],
  },
  {
    key: 7,
    text: "Do you trust me? Tell me your secret.",
    choices: [
      {
        text: "I'm really just white trash with a pretty face",
        maven: "maude",
      },
      { text: "My stress level is out of control", maven: "mary_jo" },
      { text: "I'll never live up to a family member", maven: "eleanor" },
      { text: "I like numbers more than people", maven: "lulu" },
      { text: "I love squeeze cheese!", maven: "natasha" },
    ],
  },
  {
    key: 8,
    text: "Have a hero? Who do you aspire to be?",
    choices: [
      { text: "Athena", maven: "aggie" },
      { text: "Gloria Steinem", maven: "eleanor" },
      { text: "Florence Nightengale", maven: "jordan" },
      { text: "Marie Curie", maven: "lulu" },
      { text: "Sophia Loren", maven: "desiree" },
    ],
  },
  {
    key: 9,
    text: "Want to feel accomplished? What's your deepest passion?",
    choices: [
      { text: "Family", maven: "maude" },
      { text: "Be my authentic self", maven: "mary_jo" },
      { text: "Host world leaders", maven: "tess" },
      { text: "Men", maven: "desiree" },
      { text: "Host a cooking show", maven: "natasha" },
    ],
  },
];
